on:
  push:
  workflow_dispatch:

jobs:
  test-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
            python-version: 3.9
            cache: pip

      - name: Check versions
        run: pip freeze
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Check versions
        run: pip freeze
